CREATE TABLE USUARIO (
	ID INTEGER IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL
	PASSWORD VARCHAR(256) NOT NULL
);

INSERT INTO USUARIO VALUES (1, 'kurt', 'a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=');

